"""fixed_mood_entry

Revision ID: 51504476500f
Revises: e55eb2620bef
Create Date: 2026-01-16 03:00:58.371252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51504476500f'
down_revision: Union[str, Sequence[str], None] = 'e55eb2620bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood_entries', 'mood',
               existing_type=postgresql.ENUM('HAPPY', 'SAD', 'ANGRY', 'CALM', 'TIRED', 'EXCITED', 'ANXIOUS', name='moodtype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood_entries', 'mood',
               existing_type=postgresql.ENUM('HAPPY', 'SAD', 'ANGRY', 'CALM', 'TIRED', 'EXCITED', 'ANXIOUS', name='moodtype'),
               nullable=False)
    # ### end Alembic commands ###
