"""fix_missing_columns

Revision ID: e55eb2620bef
Revises: 
Create Date: 2026-01-16 02:53:42.420575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55eb2620bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_entry_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_entries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_entries')
    op.drop_column('users', 'last_entry_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
